[package]
name = "cifar-10"
version = "0.1.0"
authors = ["chrism <christopher.and.moran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#name = "cifar_10"

[dependencies]
ndarray = "0.13"
image = "0.23"
rand = "0.7"
minifb = "0.17"